### ISSUE TITLE
Error feedback to users

### ISSUE THREAD

**Issue by harabalos** [robotics-4-all/dFlow#5]
Description:
---------------
In our current implementation, when the model calls a service and doesn't receive a successful response (e.g. not a 200 status), the system prints an error message to the terminal but doesn't provide feedback to the end user.

Objective:
---------------
To improve the user experience, we should inform the user when something goes wrong through a user-friendly message.

**Comment by GMANIOUDAKI** [comment]
Is this issue still relevant? If so, are there any specific technologies or frameworks for these calls I could focus on?

**Comment by harabalos** [comment]
Absolutely, it's still relevant. I would recommend to see the Rasa framework and especially the dispatcher method.

**Comment by GMANIOUDAKI** [comment]
Thank you for your feedback! I'm working on this issue.
